### ISSUE TITLE
Images and design

### ISSUE THREAD

**Issue by ghost** [localgovdrupal/localgovdrupal.org#17]
We need to think about images for the site
e.g. better designed version of the governance graphic - plus some kind of council / person / head shot collage for the about us page

**Comment by msayoung** [comment]
@aaronhirtenstein - we may need to decide on a diagram that describes the LGD structure, do you have any thoughts about that? 
Re: headshots. There were some early shots of in person meetings, but otherwise it's been virtual meetings. The Product Group meeting has an interesting bunch of faces, but we may need permission to publish. 
cc @willguv @MichaelDCR

**Comment by finnlewis** [comment]
@TJHDCR we're removed the image from https://production.localgovdrupal.org/about-lgd/governance  in favour of something else... maybe without people' names on.

**Comment by finnlewis** [comment]
We've got some other images here https://docs.google.com/presentation/d/1CeEykEb5mOy_cFb2AHs9QU5a04S73ixr3XUSGGbkcbI/edit#slide=id.ge644c6e4ef_0_174

But @msayoung is keen that if we put up an image it represents more reality than historical ideas. Something that is not untrue!

**Comment by MichaelDCR** [comment]
we can live without an image for now, and then get one made when we figure out the actual structure
