### ISSUE TITLE
Shop Window Website: write Developer intro content 

### ISSUE THREAD

**Issue by MichaelDCR** [localgovdrupal/localgovdrupal.org#5]
Rough first draft is fine, we can polish

This is for a sales-type page that gives an overview of LGD for developers and why it's just a whole bunch of good things for them. So doesn't have to be deep in technical detail, c400 words should be fine, longer is fine too :)

We will add some nice quotes. 

Suggestions for copy (but you will have a much better idea of what to say for devs):
- for in house council devs & agencies 
- out of the box install 
- collaborative working 
- contributing 
- quality of code / testing 
- working methods - Releases / Code Reviews / Issues / Bugs 
- github / documentation (we will add links to the actual documentation)

**Comment by MichaelDCR** [comment]
Drive folder for drafts - https://drive.google.com/drive/folders/1uDCOKAP6-fmq_zPgXDKHfCK-9_iowJwK

**Comment by finnlewis** [comment]
@MichaelDCR I've written a first draft https://production.localgovdrupal.org/web-teams/developers

I'll read again and improve, but it might be good enough for starters! 

CC @msayoung any thoughts?

**Comment by msayoung** [comment]
Good first draft @finnlewis 

I fiddled with the Heading Levels and spacing. 

Thinking out loud: What do you think about reordering the sections after "Why choose .." - putting the most riveting at the top. I also wonder about numbering the sections so that they are clearly all answers to the question. 

Maybe:

1. Technically excellent (loads of features, Drupal best practice)
2. Modular
3. Flexible (a starting point)
3. Automated testing
4. Peer review
5. Community and collaboration
6. Easy to try (quick start and demo)

**Comment by MichaelDCR** [comment]
@msayoung yes good idea to re-order with main benefits first, will do that

we aren't numbering points elsewhere so it would be inconsistent

**Comment by MichaelDCR** [comment]
sorry @msayoung - see you've suggested some other edits too - do you want to edit the page as you understand the technical side better

**Comment by MichaelDCR** [comment]
ok, I have made some edits if you'd like to review - https://production.localgovdrupal.org/web-teams/developers

**Comment by finnlewis** [comment]
Looks wonderful! Thanks both @msayoung  and @MichaelDCR
